import type { Metadata } from "next";
import "./globals.css";
import Header from "./header/page";
import { GlobalState } from "@/context";
import {Ubuntu} from 'next/font/google'

const font =Ubuntu({ subsets: ['latin'], weight: ["300", "400", "500", "700"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head> <meta name="viewport" content="width=device-width, initial-scale=1.0" /></head>
      <body className={font.className}>
        <Header />
        <GlobalState>
          {children}
        </GlobalState>
      </body>
    </html>
  );
}
